### ISSUE TITLE
Having an external script refresh the widget

### ISSUE THREAD

**Issue by blahsd** [felixhageloh/uebersicht#310] opened 2018-03-20 19:49 UTC
Ok, I'm starting to feel bad because I'm opening so many issues. Be patient with me, I am shit at this and need lots of help – also feel free to ignore me. 

Anyways.

I'm attempting a widget that works as a settings panel for the _other_ widgets. So in order to do that, I have a script that changes the content of the applied css file to whatever argument is passed, than refreshes Ubersicht. This is the script: 

```
cd [path of the css' folder]/styles

cp "$1.css" 'applied.css'

osascript -e 'tell application "'$(ps ax | grep sicht | awk '{print $5}' | head -1 | cut -d/ -f3 | cut -d. -f1)'" to refresh'
```

And it works fine and dandy when I run it from the command line with

`sh selectstyle.sh [name of theme]`

Now for the fun part.

I want this script to be run from within the widget, obviously, so the "settings panel" has this code in the afterRender:

`$(domEl).on 'click', ".opt", (e) => @run "sh [path of script's folder]/selectstyle.sh #{ $(domEl).find($($(e.target))).attr('id') }"`

where the clicked button's ID is the name of an available css file. What happens is:
1. Click on the button
2. Content of the applied theme changes
3. Ubersicht does not refresh
(4.) If I reload Ubersicht manually, the theme has been set to whatever button I clicked

Only thing I'm getting in the console is a 500: Internal Server Error, which I don't know how to investigate more.

This is all absolutely incomprehensible to me.

Does anybody know how this is supposed to work? Is there an internal function for refreshing _all_ widgets? 

Thanks!

**Comment by felixhageloh** [comment] 2018-04-03 17:30
not ignoring you btw, just had a very busy month :)

Did you manage to figure this out? I think the problem is that your are calling your shell script with `sh`  which will fork another shell. I need to double check this, but I can imagine that this causes problems. In any case, the error message returned in the console should ideally also give you more details

**Comment by felixhageloh** [comment] 2018-04-03 17:30
closing this as a question, but feel free to follow up

**Closed by felixhageloh** 2018-04-03 17:30 UTC

**Comment by blahsd** [comment] 2018-04-04 12:29
No worries dude, I've been up your ass quite a bit – actually, thanks for bearing with me for so long.
Haven't figured this one out yet but will report back when I do – might be helpful for others

**Comment by blahsd** [comment] 2018-04-04 12:33
By the way you're also really smart and what you said fixed it. By doing 
`chmod +x [SCRIPT PATH]`
and then calling in from within the widget like this: 
`  $(domEl).on 'click', ".opt", (e) => @run "[SCRIPT PATH]"`
without calling it through `sh` makes it work correctly.

Thanks!
