### ISSUE TITLE
"Error" every few refreshes since 1.3

### ISSUE THREAD

**Issue by fschulze** [felixhageloh/uebersicht#340] opened 2018-11-23 11:26 UTC
Since the 1.3 release I get an error instead of my widget every few refreshes. I don't know the exact wording. It's a light grey box. I'm using a shell script which calls a python script which returns HTML. It worked without issues until 1.3. The errors also show in the debug console, but I couldn't find useful (to me) detail. Unfortunately the errors where gone after I closed the debug console and it didn't happen the last 15 minutes. There was also a resource not found error for ``127.0.0.1.../run`` if I remember correctly.

**Comment by fschulze** [comment] 2018-11-23 11:30
The text is "error running command", but it didn't show in the debug console this time.

I have a dual screen setup and it was only on one of the screens (not the main one).

**Comment by felixhageloh** [comment] 2018-11-23 11:30
are you on 1.3.56?

**Comment by fschulze** [comment] 2018-11-23 11:39
Yes, I'm on 1.3.56

Now I got it in the log:
```
[Error] status-coffee:
Error: error running command
wrapError — client.js:1:749223
(anonymous function) — client.js:1:749459
callback — client.js:1:719471
crossDomainError — client.js:1:719801
onreadystatechange — client.js:1:720914
	redraw (client.js:1:734729)
	(anonymous function) (client.js:1:733256)
	callback (client.js:1:719471)
	crossDomainError (client.js:1:719801)
	onreadystatechange (client.js:1:720914)
```
```
[Error] Failed to load resource: The network connection was lost. (run, line 0)        
http://127.0.0.1:41416/run/
```

**Comment by felixhageloh** [comment] 2018-11-23 11:42
It does look like an error that was fixed in 1.3.56. Can you ensure that if you check for updates, that you are on the latest version?

**Comment by felixhageloh** [comment] 2018-11-23 11:42
if you are, can you provide the command you are trying to run?

**Comment by fschulze** [comment] 2018-11-23 11:56
The about box says I am and checking for updates says I got the latest.

The only widget in the folder is:
```
command: "/PATH TO SH SCRIPT"

# the refresh frequency in milliseconds
refreshFrequency: "30s"
```
That script sets some environment variables and then calls the Python script:
```
#!/bin/sh
export LANG="en_US.UTF-8"
export LC_COLLATE="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export LC_MESSAGES="en_US.UTF-8"
export LC_MONETARY="en_US.UTF-8"
export LC_NUMERIC="en_US.UTF-8"
export LC_TIME="en_US.UTF-8"
export LC_ALL=
/PATH TO PYTHON SCRIPT $*
```

Did something about multi-monitor change with 1.3? I think with 1.2 it only ever was on the main screen, but I'm not sure. The error only shows on one screen, the other is fine. The screen changes from time to time. The debug log only shows the errors from the main screen.

Could it be that the python script is called twice in very short succession to fill both screens?

**Comment by felixhageloh** [comment] 2018-11-23 12:07
Ok, I see!
What changed in 1.3.55 is that Übersicht is more explicit about errors, so this is likely an error that occurred in the past but went unnoticed. 

I discovered that Safari (which is what Übersicht uses under the hood) would sometimes kill requests because it was expecting a different 'keep-alive' timeout than the server was using. This was fixed in 1.3.56

You error looked like the one mentioned above, but now that I look at it again it seems to be slightly
different. Is it possible that your script times out or errors when called in short succession?

**Comment by fschulze** [comment] 2018-11-23 12:13
It's possible that it fails when called quickly. I'll add some logging to it to find out.

**Comment by yu-george** [comment] 2018-11-30 10:47
I think my error in #334 is the same one as this, since we both commands are running a Python script. I will try to see what is going on. Are other commands (such as direct shell commands without running any extra scripts) working as usual?

**Comment by fschulze** [comment] 2018-11-30 11:34
I added piping of stderr to a log file in my sh wrapper script and the python script seems to run fine, no error output when I see the error message.

**Comment by felixhageloh** [comment] 2018-11-30 12:23
Interesting. As far as I can tell,  bash scripts are working as usual.

Maybe two things to check:
- What version of macOS are you running? 
- does the script sometimes exit with a non-zero exit code?

**Comment by fschulze** [comment] 2018-11-30 13:13
10.13.6

In earlier versions of Übersicht when there was an error the output was just in place of the HTML. Could you maybe add some more info to logging with the exit code and maybe the output?

I doubt the shell script itself produces an exit code and when my Python script has a non zero exit code it should have output on stderr as well. I will see if I can log the exit code.

**Comment by felixhageloh** [comment] 2018-12-03 08:11
@fschulze that should still be the case, so I am guessing something else is going wrong here. 

I am on the latest macOS, which is maybe why I am not seeing this error. @yu-george are you on 10.13 as well?

**Comment by yu-george** [comment] 2018-12-03 08:16
@felixhageloh I am on the latest OS, i.e. 10.14.1 (18B75). I don't think my script has an exit code. I don't think my Python script has any error, it works fine when I run it from iTerm 2 using the same command.

**Comment by felixhageloh** [comment] 2018-12-03 08:58
ok so it is not about the macOS version either. 
Bit of a stab in the dark, but could you try running the python command in unbuffered mode (using the `-u` flag`) and see if that changes anything?

**Comment by fschulze** [comment] 2018-12-04 10:11
@felixhageloh I added ``-u`` with no difference (except that it might happen less often, not sure)

I added logging of the time and exit code to my wrapper script. Since then I had one error in the debug console (which I missed unfortunately) and there was no non zero exit code in the log. Unfortunately the debug console doesn't show the time of the error (or I don't know where it is), so I can't correlate it in the logs. I suspect the script isn't called at all when the error happens. Because of the following part of the error:
```
[Error] Failed to load resource: The network connection was lost. (run, line 0)        
http://127.0.0.1:41416/run/
```

If I can get the time somehow and correlate the two, then I can say more about that. It seems like Übersicht calls the script every 30 seconds (plus the time it takes for the script to run)

**Comment by felixhageloh** [comment] 2018-12-05 10:38
Thanks for you debugging efforts! I'm pretty convinced now it is the same issue as the one that (I thought) was fixed in 1.3.56. 

The problem is that I can't reproduce it. I've been running simple test widget calling python every 30s, for a few days now, but no errors so far. 

Could you maybe share your widget so I can try reproducing the error that way?

**Comment by fschulze** [comment] 2018-12-05 11:53
I don't think it's python related. Even the wrapper script where I do the logging isn't called at all when the error happens. It fails before executing it. Where is the ``http://127.0.0.1:41416/run/`` URL going to which fails the connection? Is that a server part in Übersicht?

**Comment by fschulze** [comment] 2018-12-07 11:08
I fetched the repo, removed the uglify step for client.js and copied the result into the Übersicht App.

I know the output is generated from coffee script, but maybe this helps. In this function:
```js
  redraw = function(error, output) {
    var e;
    if (error) {
      contentEl.style.fontFamily = 'monospace';
      contentEl.style.fontSize = '12px';
      contentEl.style.whiteSpace = 'pre';
      contentEl.style.background = '#fff';
      contentEl.style.padding = '20px';
      contentEl.innerHTML = error.message + '\n' + (error.lines || '');
      console.error(implementation.id + ":", error, output);
      return rendered = false;
    } else {
      contentEl.style.fontFamily = '';
      contentEl.style.fontSize = '';
      contentEl.style.whiteSpace = '';
      contentEl.style.background = '';
      contentEl.style.padding = '';
    }
    try {
      return renderOutput(output);
    } catch (error1) {
      e = error1;
      return redraw(e);
    }
  };
```
which is arount line 37746 in the generated output the error logging is happening in the ``if (error) {`` part. I added the ``output`` to the logging and it's ``undefined``.

Again my script wasn't called at all. Notice the 60s gap instead of the regular 30s gap:
```
Fri Dec  7 12:01:11 CET 2018
0
Fri Dec  7 12:02:12 CET 2018
0
```

It looks to me like the ``client.js`` side has issues with the connection to the ``server.js`` side when this happens. This is also indicated by the error about the lost network connection to ``http://127.0.0.1:41416/run/``.

**Comment by felixhageloh** [comment] 2018-12-07 11:35
@fschulze thanks again!
I know where the error happens by now, the main problem for me is that I can't reproduce it. So we'll have to do it this way: can you try this build and see if you still get the error?
https://www.dropbox.com/s/2xg4fm9sxhge7ok/Uebersicht-no-keep-alive.app.zip?dl=0

**Comment by fschulze** [comment] 2018-12-07 12:14
I can't reliably reproduce it either. It just happens every few hours. I'm running that build now and will let you know if it should happen again. Otherwise I'll tell you know in a few days that there were no more issues.

**Comment by felixhageloh** [comment] 2018-12-10 12:12
has the error occurred again in the meantime @fschulze ?

**Comment by fschulze** [comment] 2018-12-10 13:06
@felixhageloh no, but I haven't used my computer over the weekend, so it's only been a few hours usage in total so far

**Comment by felixhageloh** [comment] 2018-12-10 13:07
good to hear you haven't used your computer over the weekend 😄 . I'll ping you in a few days again then

**Comment by DevPoetsSociety** [comment] 2018-12-11 22:57
I've been having the same problem (macOS 10.13.6), and running the 'no keep alive' build still has the same thing happening (possibly less often?) Here's an [example](https://imgur.com/Ks6fcca) of two widgets, the [left one](http://tracesof.net/uebersicht-widgets/#outdated-brew-formulae) having the problem and the right not (it varies which is affected.)

**Comment by felixhageloh** [comment] 2018-12-12 14:05
@fschulze do you also still get this error?

**Comment by fschulze** [comment] 2018-12-12 14:50
@felixhageloh so far, no

**Comment by felixhageloh** [comment] 2018-12-12 15:44
@DevPoetsSociety are you sure you are experiencing the same error (Network connection closed)?

**Comment by DevPoetsSociety** [comment] 2018-12-12 17:14
Looks like internal server error. 

![screen shot 2018-12-12 at 11 02 00 am](https://user-images.githubusercontent.com/13501586/49886239-1bd57400-fe07-11e8-8c69-42ce27b9ebf1.png)

**Comment by yu-george** [comment] 2018-12-13 11:20
@felixhageloh I used your no-keep-alive version, and the error has not came up so far. I will keep you updated if it comes up again. Thanks.

**Comment by R-E-T** [comment] 2018-12-16 14:08
I can only reproduce the error for widgets that make use of Python programs. Parsing e.g. the results of a REST API with the same frequency (here: 2 secs) does not result in this error/glitch. (macOS 10.14.2 and tested both, official and "Dropbox" version with identical results)

**Comment by felixhageloh** [comment] 2019-05-30 09:27
This should be completely fixed now hopefully. Let me know if it still happens

**Closed by felixhageloh** 2019-05-30 09:27 UTC

**Comment by fschulze** [comment] 2019-05-30 15:52
I haven't had the issue in a while. In fact, I think it now shows an occasional error in my script properly. Thanks!

**Comment by kavinvalli** [comment] 2021-11-28 11:50
Hi @felixhageloh I'm having this issue for a while now with [simple-bar](https://github.com/Jean-Tinland/simple-bar)
