### ISSUE TITLE
Übersicht Menu Bar Icon leaves gap after quitting

### ISSUE THREAD

**Issue by NullTheFool** [felixhageloh/uebersicht#134] opened 2015-10-30 07:09 UTC
OSX Yosemite 10.10.5
Examples:
Starting Icon order: [ (WiFi) ]

-Übersicht and Alfred 2
1) Start Übersicht from launchpad
Icon order: [ (Übersicht) (WiFi) ]
2) Start Alfred 2 from launchpad
Icon order: [ (Alfred) (Übersicht) (WiFi) ]
3) Quit Übersicht
Gap remains in Übersicht's place: [ (Alfred) (-empty gap-) (WiFi) ]

-Übersicht and f.lux
(reversing steps 1 and 2 yields same results)
1)Start Übersicht from launchpad
Icon order: [ (Übersicht) (WiFi) ]
2) Start f.lux from launchpad
Icon order: [ (Übersicht) (f.lux) (WiFi) ]
3) Quit Übersicht
Gap remains in f.lux's place: [ (Übersicht) (-empty gap-) (WiFi) ]

Don't know if this is a general issue caused by certain icons in the menu bar but so far I have only encountered this with Übersicht.

**Comment by felixhageloh** [comment] 2015-11-06 14:34
I can conform this is a bug and know what the issue is. Thanks for reporting!

**Comment by felixhageloh** [comment] 2015-11-19 08:25
This should be fixed since 0.6

**Closed by felixhageloh** 2015-11-19 08:25 UTC
Labels: bug
