### ISSUE TITLE
Ubersicht taking(?) click events on yabai 3.0.2

### ISSUE THREAD

**Issue by arulagrawal** [felixhageloh/uebersicht#401] opened 2020-05-26 10:17 UTC
When using yabai 3.0.2 and Ubersicht 1.4 together and I change workspaces then left click in a window to try and interact with it, that window *loses* focus, and it seems like text is being selected in my ubersicht bar.

It seems like when I change the workspace with the trackpad gesture this bug occurs but not when I use a keyboard shortcut but I'm not sure about this.

I was pretty sure I had never seen this happen before, and sure enough if I download the 3.0.1 release and just run the pre-built binary this behaviour does not occur.

I've tried to capture this [here](https://www.youtube.com/watch?v=_nenywtjJ4c&feature=youtu.be). You can see discord/spotify losing focus when I left click on them after a workspace change, and text in ubersicht being selected at the top.

[here](https://github.com/koekeishiya/yabai/issues/535) is the same issue posted on the yabai repo

**Comment by AlaaMansourTW** [comment] 2020-05-28 11:52
I'm also facing the same issue

**Comment by Ninja73737** [comment] 2020-05-30 20:37
Same issue here, big problem...

**Comment by kkga** [comment] 2020-06-10 08:39
This is super annoying and I have to restart ubersicht multiple times a day. Have anyone found a solution?

**Comment by koekeishiya** [comment] 2020-06-11 09:59
Resolved on the latest yabai master. See my comment: https://github.com/koekeishiya/yabai/issues/535#issuecomment-642544288

I would still argue that this is a design flaw with regards to how Übersicht is implemented, and would suggest that it be improved upon.

**Comment by felixhageloh** [comment] 2020-06-14 12:34
@koekeishiya do you have some pointers what could be improved for Übersicht? I had a quick glance at the issue mentioned in your repo, but I could not immediately understand what the issue is (it's been a while since I worked on this)

**Comment by koekeishiya** [comment] 2020-06-14 14:21
My initial thought was that übersicht would pass through click events to the underlaying window when that click did not hit an actual widget drawn in the window, by setting the windows event shape.

I did however manage to resolve the issue by ignoring windows that report as AXUnkown through the accessibility API and I think this is an acceptable solution, so you don’t actually need to change anything.

The issue was that yabai would change the window level of the übersicht window to always stay on top, making it take all click events. I assume it was never meant to operate at any level other than the desktop-level, which is why this has not been an issue in the past.

I think you can probably close this issue, as it is resolved in an acceptable way in yabai.

Sent from my iPhone

On 14 Jun 2020, at 14:34, Felix <notifications@github.com> wrote:

﻿

@koekeishiya<https://github.com/koekeishiya> do you have some pointers what could be improved for Übersicht? I had a quick glance at the issue mentioned in your repo, but I could not immediately understand what the issue is (it's been a while since I worked on this)

**Closed** 2020-08-12 12:48 UTC
