### ISSUE TITLE
How to style the global scope of a widget properly with JSX?

### ISSUE THREAD

**Issue by obetomuniz** [felixhageloh/uebersicht#299] opened 2018-01-02 03:18 UTC
Do we have some type of export function/constant? Like:

```
export const styles = `
  background-color: red;
`;
```

**Comment by felixhageloh** [comment] 2018-01-02 09:18
yeah that should work

**Comment by felixhageloh** [comment] 2018-01-02 09:18
closing this, since it is a question, but feel free to follow up!

**Closed by felixhageloh** 2018-01-02 09:18 UTC

**Comment by obetomuniz** [comment] 2018-01-02 14:04
It's not working, so it's a bug.

My widget:
```
const x = 'Test';

export const styles = `
  background-color: red;
`;

export const command = `echo ${x}!`

export const refreshFrequency = 5000

export function updateProps(prev, action) {
  return {
    output: action.output
  };
}

export function render(props) {
  return <div>
    {props.output}
  </div>;
}
```

**Comment by felixhageloh** [comment] 2018-01-02 14:06
can you provide details on what is not working?

**Comment by obetomuniz** [comment] 2018-01-02 14:07
As I asked, I can't set the `background-color: red` to the root of my widget.

**Comment by obetomuniz** [comment] 2018-01-02 14:15
This is what my widget above is rendering...

![screen shot 2018-01-02 at 12 14 39](https://user-images.githubusercontent.com/1680157/34486333-87af8f5e-efb6-11e7-9d1d-0037b4521bfc.png)

**Comment by felixhageloh** [comment] 2018-01-02 14:16
sorry, I don't see that question anywhere. Either way, for this widget to work you probably need:

```js
const styles = {
  backgroundColor: 'red';
};
``` 
so an object, not a string. You also don't need export here, unless you are importing the style somewhere else.

And then:

```jsx
 export function render(props) {
  return <div style={style}>
    {props.output}
  </div>;
}
```

i.e. you need to set the style prop in your jsx

**Comment by obetomuniz** [comment] 2018-01-02 14:20
As you can see below @felixhageloh , following your tip, it is still not styling the base of the widget (e.g.  The widget base is the `<div id="widgets-sample-jsx">` element).

![screen shot 2018-01-02 at 12 19 03](https://user-images.githubusercontent.com/1680157/34486436-256325c6-efb7-11e7-9cf7-299149448bb4.png)

**Comment by felixhageloh** [comment] 2018-01-02 14:24
the outer wrapper div is for internal use. The base of your widget is actually the div with the style prop

**Comment by obetomuniz** [comment] 2018-01-02 14:28
🤔  It clarifies more. Thanks 👍 !  Anyway, it's applying that `widget` class. I would love to have a `position: relative` there.

**Comment by obetomuniz** [comment] 2018-01-02 15:01
BTW, I'm not able to control the widget alignment with the `top`, `bottom`, `left`, and `right` using your proposals. As the `widget` class have the `position: absolute` value, it is locking any child component with `position: absolute`. It's weird cuz the CoffeeScript version has a different approach.

**Comment by felixhageloh** [comment] 2018-01-03 10:21
you are right this is a bug! You can only position widgets top left

**Comment by felixhageloh** [comment] 2018-01-03 10:25
btw, using `position: 'fixed'` works, but that is not how it was intended to work.

Having said that, I am still working on styling for JSX widgets. Ideally I'd have a solution that does not rely on inline styles.
