### ISSUE TITLE
Not working when screens are mirrored 

### ISSUE THREAD

**Issue by DeCatOfDestruction** [felixhageloh/uebersicht#173] opened 2016-02-26 03:04 UTC
Is there any way back to download old version 7.0? thanks

**Comment by evanfuture** [comment] 2016-02-26 07:27
Maybe we can turn this into a proper issue.  I am having a specific problem with the new version, that plugging in a external monitor into my Macbook pro with mirroring turned on causes all the widgets to disappear.  I'm guessing they're on the now invisible original screen.

I've tried changing their screen settings, tried opening the Debug console, which is also missing.  Everything works fine when I'm either not in mirroring mode, or the screen is unplugged.

Thoughts?

**Comment by felixhageloh** [comment] 2016-02-26 08:05
thanks @evanfuture I think I have a fix - will try to release asap. 

@DeCatOfDestruction is this the same issue you were having?

**Comment by felixhageloh** [comment] 2016-02-26 16:39
Here is a link to a new version: http://tracesof.net/uebersicht/releases/Uebersicht-0.8.31.app.zip
Let me know if it fixes your issues!

@DeCatOfDestruction and just in case, here is a link to the previous version http://tracesof.net/uebersicht/releases/Uebersicht-0.7.25.app.zip

**Comment by EnglishLFC** [comment] 2016-02-26 22:22
I tried 0.8.31 and it does not work. My logs have this message repeated over and over:

26/02/2016 5:16:57.731 PM Übersicht[40458]: http://127.0.0.1:41416/69732992 failed to load: The request timed out. Reloading...

This is true for both 0.8.3 and 0.8.31

Version 0.7 works fine.

**Comment by evanfuture** [comment] 2016-02-27 07:15
I won't be back with my big monitor until Monday, but I'll be able to tell you if it works as soon as I'm in the office.  Thanks for being on top of things Felix, great work.

**Comment by evanfuture** [comment] 2016-02-29 07:27
Ok, an update.  I plugged in the monitor, and installed the patched version, and things sort of worked, but when I would edit the widget files, or use the debugger, widgets started being duplicated.  Also happened when I toggled some of the option/command/ctrl keys.  So to fix it I restarted the app, but now its back to Friday's behaviour of not showing...

Everything runs just fine on the normal screen though.

**Comment by felixhageloh** [comment] 2016-02-29 08:27
@evanfuture ok thanks for the update! I will see if I can reproduce

**Comment by felixhageloh** [comment] 2016-02-29 08:50
new link that should fix the duplication issue http://tracesof.net/uebersicht/releases/Uebersicht-0.8.32.app.zip

**Comment by evanfuture** [comment] 2016-02-29 15:59
I can confirm that it fixes the duplication issue, nice fast work!

The second monitor/mirrroing issue doesn't budge...  I think the issue is that the MacBook's screen is mirroring the Thunderbolt display, not the other way around.  So, when I first plug in, my primary screen is the macbook and the thunderbolt is a 2nd screen, but when I turn on mirroring, both windows are "optimized for Thunderbolt display".

**Comment by felixhageloh** [comment] 2016-02-29 16:08
Glad that the duplication is gone at least :). 
So the problem is still that widgets are not showing when you plug in the external Thunderbolt display? Also, what screen settings do you use for your widgets? Show on all screens? Show on main screen? Show on selected screens?

**Comment by felixhageloh** [comment] 2016-02-29 17:00
@EnglishLFC I've created a separate ticket for the issue you are having https://github.com/felixhageloh/uebersicht/issues/176

**Comment by evanfuture** [comment] 2016-03-01 04:20
Yes, neither the widgets, nor the debugger show when I plug in an external thunderbolt display with mirroring turned on.  Works fine with mirroring off.

For all the widgets I use Show on All Screens, though I have tried changing them with no luck.

**Comment by felixhageloh** [comment] 2016-03-01 07:38
Thanks and sorry for digging deeper to try and reproduce this issue. 
Could you try to run `rm ~/Library/Application\ Support/tracesOf.Uebersicht/WidgetSettings.json` in your terminal and see if that fixes anything?

If not can you open Console.app and then start Übersicht and see what get's logged. It should look something like this: 
![screen shot 2016-03-01 at 8 37 46](https://cloud.githubusercontent.com/assets/367503/13420738/f9ee83f8-df88-11e5-8b30-eab93d8d4c0b.png)

**Comment by evanfuture** [comment] 2016-03-01 10:53
01/03/16 11:53:13,675 Übersicht[56826]: starting server task
01/03/16 11:53:14,055 Übersicht[56826]: watching /Users/evanpayne/Library/Application Support/Übersicht/widgets
01/03/16 11:53:14,068 Übersicht[56826]: server started on port 41416
01/03/16 11:53:14,070 Übersicht[56826]: using 0 screens

**Comment by felixhageloh** [comment] 2016-03-01 11:00
0 screens is not good :). Can you double check that your are running the pre-release version  http://tracesof.net/uebersicht/releases/Uebersicht-0.8.33.app.zip but selecting 'About Übersicht' in the menu? You sometimes have to hunt for the window that pops up because it is behind other windows. 

![screen shot 2016-03-01 at 11 57 59](https://cloud.githubusercontent.com/assets/367503/13425105/0335144c-dfa5-11e5-83e1-848ff50bac3e.png)

I'm asking because you mentioned that it was working temporarily and the logs show exactly what you would expect in the version _before_ the fix.

**Comment by evanfuture** [comment] 2016-03-01 11:15
Its odd, I just downloaded the link you posted, quit the app and replaced the version with the one you sent, and the About window still shows Version 0.8 (30)...

**Comment by felixhageloh** [comment] 2016-03-01 11:18
ah that explains :). OS X is quite smart when you modify apps that are currently running. It will keep the old version around and even find it in the trash etc. 
The easiest way to be sure is to download the pre-release again, rename it to Übersicht-beta or whatever you like and then run it

**Comment by evanfuture** [comment] 2016-03-01 11:24
Perfect.  Issue solved!

**Comment by felixhageloh** [comment] 2016-03-01 11:46
great! Will be released soon then

**Comment by felixhageloh** [comment] 2016-03-02 08:08
should be fixed with version 0.8.35

**Closed by felixhageloh** 2016-03-02 08:08 UTC
Labels: bug

**Comment by DeCatOfDestruction** [comment] 2016-03-07 06:32
good job! I have updated uebersicht to new version & it works just like old times.
the issue i met is the Blur Widget (https://github.com/atika/Ubersicht-Blur), and i also update it just now : )
