### ISSUE TITLE
Background blur works intermittently

### ISSUE THREAD

**Issue by Pe8er** [felixhageloh/uebersicht#172] opened 2016-02-24 18:22 UTC
This is related to my [Sidebar.widget](https://github.com/Pe8er/Sidebar.Widget).

The following CSS in my `main.coffee` enables blur on all widgets:

`-webkit-backdrop-filter: blur(16px);`

I have noticed that in the latest version of Ubersicht, blur sometimes turns itself off:

![Screenshot](http://imgur.com/AlZ0xdY.jpg)

Console shows two errors, although I don't think they're relevant:

![screenshot](http://imgur.com/RqZ9mmq.jpg)

Any idea what is happening? :) Please let me know if there is any other info I can give you to help debug.

**Comment by felixhageloh** [comment] 2016-02-25 08:20
Yeah the web view is a bit lazy with re-rendering sometimes :/. I already have a few places were I need to  'kick' it a bit to redraw these backdrop-filters, but I guess I'm missing some. Does this happen when you switch workspaces or something, or just by itself when the widget updates?

The errors are probably unrelated, but if this happens every time you get an error it could be a clue.

**Comment by Pe8er** [comment] 2016-02-25 18:55
Some observations, hopefully helpful:
- when I rename CSS property to `backdrop-filter` it doesn't work at all (side note: when I make changes to my `main.coffee`, refreshing it doesn't work. I have to restart Ubersicht)
- when the computer wakes from sleep it doesn't work
- when switching spaces it's okay
- when desktop picture changes automatically it's ok

**Comment by felixhageloh** [comment] 2016-02-25 19:50
@Pe8er great that helps!
Btw `backdrop-filter` doesn't work because Safari (which is what Übersicht uses) only supports it with the `-webkit` prefix (it is also the only browser that supports it at all).

**Comment by CarlosMed** [comment] 2016-02-25 23:28
@felixhageloh Just a curious but why did you choose Safari web view over chrome?

**Comment by Pe8er** [comment] 2016-02-25 23:49
@felixhageloh I just discovered that if change picture is set to 30 minutes or one hour, some widgets don't update blur after desktop picture was changed. When I had it set to 5 seconds, all of them were updating correctly.

**Comment by felixhageloh** [comment] 2016-02-26 11:03
@CarlosMed it's the default web view you get from when developing apps in Cocoa (Apple's framework for developing OS X apps)

**Comment by felixhageloh** [comment] 2016-02-26 11:05
saying Safari is actually a bit misleading - it is just WebKit but you always get the WebKit version that Safari is using currently

**Comment by felixhageloh** [comment] 2016-07-10 19:16
this might be fixed in version 1.0.42 released today, please let me know!

**Comment by Pe8er** [comment] 2016-07-10 19:51
Seems like a vast improvement! My big widget now refreshes correctly when saving script files. I'll let you know if I notice anything odd over the next few days.

**Closed** 2017-05-30 23:38 UTC

**Comment by d-fischer** [comment] 2019-01-15 09:34
This seems to still happen. Mostly when I lock my screen and unlock it again, but not always. It also seems to be per monitor - sometimes it turns off on one and still works on the other.

**Comment by rstacruz** [comment] 2020-04-27 01:14
This also happens to me when switching spaces in MacOS Catalina. Doing a manual "refresh all widgets" usually brings back the blur.

**Comment by onodera-punpun** [comment] 2021-01-08 20:53
I can confirm this still happens on big sur.

**Comment by syropian** [comment] 2022-11-01 12:35
Can also confirm this is still happening today. Each re-render seems to remove the blur for me.

**Comment by lucaorio** [comment] 2022-12-23 22:09
> Can also confirm this is still happening today. Each re-render seems to remove the blur for me.

Same for me, even with `refreshFrequency` set to `false`.

**Comment by johnsturgeon** [comment] 2023-01-31 17:06
This should be re-opened since the issue has returned.  I'll file a new issue
