### ISSUE TITLE
After killng dock uebersicht is not shown

### ISSUE THREAD

**Issue by vkravets** [felixhageloh/uebersicht#229] opened 2016-09-12 09:04 UTC
After latest update(43) after kiling Dock (used by widget to changed background) uebersicht is not shown..

Steps to reproduce:
1. Run uebersicht
2. Go to shell
3. execute killall Dock
4. Look at the desktop
=>
5. uebersicht wasn't shown

**Comment by felixhageloh** [comment] 2016-09-12 09:16
I see :/ looks like the fix for this bug https://github.com/felixhageloh/uebersicht/issues/217 breaks it.

**Comment by vkravets** [comment] 2016-09-12 10:23
It's seems yes (

**Comment by vkravets** [comment] 2016-09-13 15:23
I think we need to catch some event (may be wallpaper changed) and redraw window

@felixhageloh  Did take a time to look on it more deeply?

**Comment by felixhageloh** [comment] 2016-09-14 16:12
no not yet ... I wanted to ask tho: which widget is doing the killAll Dock? 
Basically I am thinking, restarting the Dock doesn't happen very often usually so it would be ok to also restart Übersicht in that case (it would be annoying but not an urgent issue). So I am wondering if there is a way to change the widget so it doesn't need to restart the Dock, which would make this a less urgent issue

**Comment by vkravets** [comment] 2016-09-15 12:42
All changes related to changing settings of the dock require dock to be restarted.
E.g. change wallpaper (it's uses very often who want to have random wallpaper)...

I fully agree with you but for case which I described above we should restart dock to apply changed... I search "all" the internet and didn't find right solution. All the solution without restarting dock changed only current workspace and not all workspaces... (

BTW dock can be restarted, it can be very rarely, but it can be, thus we shouldn't ignore such case also... IMHO

**Comment by vkravets** [comment] 2016-09-15 12:46
My case that I changed my wallpaper by widget since it a good scripting platform to do it )
In any case for changing wallpaper (each 3h) I need to restart Übersicht.... it's not a good idea...

If you find solution to change wallpaper programmatically without restarting dock and for all workspaces I agree with you that it not urgent issue )

For now working on 42 with fixes from 43 )

**Comment by hawkrives** [comment] 2016-09-15 12:56
Quick question, @vkravets: I haven't looked into this, but shouldn't AppleScript be able change the wallpaper without restarting the Dock? Maybe [this StackOverflow answer](http://apple.stackexchange.com/questions/141834/applescript-to-change-desktop-image-on-all-monitors)? I have no solutions, only more questions ;)

**Comment by vkravets** [comment] 2016-09-16 08:36
@hawkrives thanks for looking to my problem, but unfortunately all the solutions needs to restart Dock or chnage the background for current workspace... unfortunately this solution which you mention is not a right solution too... (

You can look all my tryings [Here](https://github.com/vkravets/dotfiles/tree/master/ubersicht/widgets/background.widget)

Code of the binary AppleScript
```
on run argv
	set wallpaper_file to item 1 of argv
	tell application "System Events"
		set theDesktops to a reference to every desktop
		repeat with x from 1 to (count theDesktops)
			set picture of item x of the theDesktops to wallpaper_file
		end repeat
	end tell
end run
```

It's very similar to yours, but it's not working for me (

**Comment by felixhageloh** [comment] 2016-09-20 17:33
sorry for the late reply - it was a busy week!
So yeah this is not a bug I want to keep having, but I'll have to research for a bit how I can solve this without breaking the other use case again.
I'm beginning tho think to make the current behavior optional, like "[ ] run in compatibility  mode. Plays nice with other apps but might have some issues". That way people that have issues in combination with other apps can enable this and it won't break for anybody else :)

**Comment by felixhageloh** [comment] 2016-09-22 15:31
Fix is on it's way!

**Comment by hawkrives** [comment] 2016-09-23 01:53
Ooh, exciting! 😉

**Comment by felixhageloh** [comment] 2016-09-23 07:23
should be fixed in 1.0.44 released today

**Closed by felixhageloh** 2016-09-23 07:23 UTC
Labels: bug

**Comment by vkravets** [comment] 2016-09-23 07:40
Great, so by default we are using old behavior. Correct? For another who uses desktop replacement should turn on the compatible mode... is it right?

**Comment by felixhageloh** [comment] 2016-09-23 08:09
exactly :)
