### ISSUE TITLE
Enhancement Request: Enable / Disable widget from Dropdown Widgets list

### ISSUE THREAD

**Issue by txt8888** [felixhageloh/uebersicht#212] opened 2016-06-22 14:16 UTC
Not sure where to make enhancement request so I added here.

could you add enable / disable (checkbox) in the widget dropdown list do the widget can be disable.  This way, I can temporarily disable all widgets but one to debug it. 

I think I can move all the *.widget folders out of the widgets folder to do the same thing, but with the option in the GUI, life is bit easier.

Also, the next feature is to disable ubersicht when computer is sleep or what not.  my laptop battery basically drain like a leaky faucet :) ...

 Thanks!

**Comment by felixhageloh** [comment] 2016-07-08 13:50
Hi, sorry for the late reply! This looks like a duplicate of https://github.com/felixhageloh/uebersicht/issues/195

About the sleep issue: as far as I know, OS X suspends all apps/processes when it goes to sleep. Can you verify that Übersicht keeps on running when you put your computer to sleep?

**Comment by felixhageloh** [comment] 2016-07-08 13:51
I'll close this issue as a duplicate for now. We can create another issue for the sleep problem if you like

**Closed by felixhageloh** 2016-07-08 13:51 UTC
