### ISSUE TITLE
Styles being stripped out of jsx widget

### ISSUE THREAD

**Issue by mhartington** [felixhageloh/uebersicht#277] opened 2017-06-05 19:59 UTC
In the latest release, it seems that styles are being stripped out of JSX based widgets.

time.widget.js

```jsx
export const refreshFrequency = 5000;
export const command = `date '+%l:%M'`;
const timeStyles = {
  paddingTop: '20px',
  fontSize: '50px',
  width: '325px',
  textIndent: '10px',
  color: '#ffffff',
  fontFamily: 'HelveticaNeue-Light'
};
export function render(props) {
  return <div style={timeStyles}>{props.output}</div>;
}
```

But the time renders without inline styles.

<img width="324" alt="screen shot 2017-06-05 at 3 58 18 pm" src="https://cloud.githubusercontent.com/assets/2835826/26800576/d0eabec8-4a07-11e7-98c6-07103bef44ec.png">

![screen shot 2017-06-05 at 3 59 02 pm](https://cloud.githubusercontent.com/assets/2835826/26800607/eee1d592-4a07-11e7-9c32-db2c0c03f59a.png)

**Comment by felixhageloh** [comment] 2017-06-06 07:43
yup I can confirm (a change in the underlying lib is causing it). Will have a fix soon!

**Comment by mhartington** [comment] 2017-06-06 12:51
You're the best!

**Comment by felixhageloh** [comment] 2017-06-09 14:42
(turned out to be a crazy busy week, but I am hoping to release the fix this weekend)

**Comment by felixhageloh** [comment] 2017-06-11 08:10
fix has been released (1.2.48)

**Closed by felixhageloh** 2017-06-11 08:10 UTC
Labels: bug

**Comment by obetomuniz** [comment] 2017-12-24 04:29
@felixhageloh This bug still appearing in the 1.2.53

**Comment by obetomuniz** [comment] 2017-12-24 04:30
![screen shot 2017-12-24 at 02 30 07](https://user-images.githubusercontent.com/1680157/34324248-6a96063e-e852-11e7-8302-28453d363fba.png)

**Comment by hawkrives** [comment] 2017-12-24 04:56
@obetomuniz Can you post a ZIP with a widget that exhibits the problem, please? That'll make it easier to test for.

**Comment by obetomuniz** [comment] 2017-12-27 12:49
Yes @hawkrives! I'll do it today asap.

**Comment by obetomuniz** [comment] 2017-12-27 22:01
Done! [to-do-list.zip](https://github.com/felixhageloh/uebersicht/files/1589949/to-do-list.zip)

**Comment by felixhageloh** [comment] 2018-01-02 09:04
@obetomuniz thanks for positing the widgets. 
It looks like the widget is trying to use [JSS](https://github.com/cssinjs/jss) styles, but is not including the JSS lib

**Comment by obetomuniz** [comment] 2018-01-02 14:00
@felixhageloh I'm not using JSS. I'm just using the `.jss` extension to avoid track a new widget in the Ubersicht menu.

**Comment by felixhageloh** [comment] 2018-01-02 14:09
I see! You can put in the file inside a folder named `lib` or `src` to avoid being detected as a widget. You will still need to actually set the style prop in your CSS

**Comment by obetomuniz** [comment] 2018-01-02 14:12
👍  Looks great! Thanks for the tip. And what about the root style? Like I mention in the issue #299 ? I'm with this same issue here.
