### ISSUE TITLE
https://127.0.0.1:41416 two process both uses 10% + CPU and Übersicht Networking uses another 5% 

### ISSUE THREAD

**Issue by mvaneijgen** [felixhageloh/uebersicht#274] opened 2017-05-25 14:27 UTC
I have around 6 widgets and all are on a 10 minute refresh or more, but like I described above I have two processes running for https://127.0.0.1:41416 and both use 10% of my CPU or more when I count every Übersicht process it uses around 25%. This isn't that much when I am doing normal stuff, but when I am working or some more have CPU activity this means that with one extra program open my laptop MPB late 2011 on 10.12.4 it will launch it selfs and tries to be a helicopter. 

Is there a way I could throttle Übersicht so that it only can use 1% of my CPU at the most, I don't need it to be accurate of anything it just to show my calendar unread emails and current todos.

- 2,8 GHz Intel Core i7
- 8 GB 1333 MHz DDR3
- Intel HD Graphics 3000 512 MB
- Übersicht version 1.1

### List of widgets 
- battery.widget
- ical.widget
- mc.widget
- simple-clock.widget
- top-cpu.widget
- weather.widget
- Wunderlist.coffee

**Comment by felixhageloh** [comment] 2017-05-28 14:59
Hey! This doesn't sound like normal CPU usage for Übersicht. Hard to tell what is going on, but here are a few things to check:

- are you running the latest version of Übersicht (1.1)?
- are there any errors in the debug console?
- does restarting your machine help?
- is there maybe a widget spinning out of control?  Could be that there is a syntax error and instead of refreshing every 10min one widget tries to refresh as fast a possible. You can try to hide widgets one by one and see if the CPU usage drops.

**Comment by mvaneijgen** [comment] 2017-05-29 16:51
@felixhageloh thanks for the replay. I am running version 1.1, but I do have a error in the debugger 

and it just keeps counting and says `(1067) WebSocket network error: The operation couldn’t be completed. Connection refused`

I have disabled all my widgets and it still keeps doing that.

**Comment by felixhageloh** [comment] 2017-05-30 06:44
I see!
So two more questions:
- you say your widgets seem to work fine, even with this error?
- is there any stack trace in the console (you can usually reveal it by clicking the triangle next to the error)?

**Comment by mvaneijgen** [comment] 2017-05-31 16:11
Thanks for the reply again. On further inspection it seem te be the issue with https://github.com/chagel/uberist which is 2 years old and the creator seems to have abandoned it. It is weird, because the plugin works fine, but I can't seem te find the code that causing the issue. 

There is nothing else in the console no 'stack trace', I think that means on which line of code the issue resights right?

**Comment by felixhageloh** [comment] 2017-06-06 06:47
yeah, the stack trace shows you the line of code the error is coming from.
How did you identify https://github.com/chagel/uberist  being the root cause? If you remove the widget, does everything work fine?

**Comment by mvaneijgen** [comment] 2017-06-06 06:51
@felixhageloh I disabled one widget I have running for 2 hours and check if my CPU was getting out of control, https://github.com/chagel/uberist was the only one that causes it hand has that error in the debugger.

**Comment by felixhageloh** [comment] 2017-06-06 07:06
ok cool, I will close this issue then, since it does not seem to be an Übersicht issue. I can try to help you with the widget tho: What is the error you are seeing?

**Closed by felixhageloh** 2017-06-06 07:06 UTC
