### ISSUE TITLE
Only display on specific desktop(s)?

### ISSUE THREAD

**Issue by shaine** [felixhageloh/uebersicht#101] opened 2015-04-28 04:13 UTC
OSX allows you to specify which desktop(s) an application will display on through the app's dock icon. It would be really nice if Übersicht allowed you to do the same - I'd like to have Übersicht running on my primary desktop, but my other desktop screens contain transparent windows that don't work well with my widgets.

Thanks for your work on this tool! I'm completely in love with it.

**Comment by felixhageloh** [comment] 2015-05-13 11:25
I think this is similar to Issue #52, right?

**Comment by shaine** [comment] 2015-05-13 15:01
Similar. #52 is looking for the ability to choose which desktop/space/screen a widget goes to, this issue is just looking for the OS-defaults on choosing which desktop the application (as a whole) will run on. This issue would probably be resolved by #52, but not vice-versa.

**Comment by felixhageloh** [comment] 2016-02-15 13:59
closing this as a duplicate of https://github.com/felixhageloh/uebersicht/issues/52

**Closed by felixhageloh** 2016-02-15 13:59 UTC

**Comment by Neto** [comment] 2018-02-07 20:44
Hey @felixhageloh!
Did you implement this option on version 1.2?
I have 3 monitors, but can't find how to choose only one monitor to show the widgets...

**Comment by felixhageloh** [comment] 2018-02-12 18:44
Hey @Neto, I did! If you go to the app icon in your menu bar (the little 'ü') you can see all your widgets listed. If you select one you can choose which screens to display it on

**Comment by Neto** [comment] 2018-02-13 17:14
Thank you!
I totally missed it :)
